import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface GenerateTopupLinkRequest {
  cardId: string;
  expiryDays?: number; // Default 30 days
}

interface OrganizationSummary {
  id: string;
  name: string;
  user_id: string;
}

interface IssuingCardRecord {
  id: string;
  organization_id: string;
  group_id: string | null;
  cardholder_name: string;
  cardholder_email: string;
  card_status: string;
  card_last4: string;
  organizations: OrganizationSummary | OrganizationSummary[] | null;
}

serve(async (req) => {
  // Handle CORS
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('🔗 Generate Top-Up Link Function Started');

    // Initialize Supabase
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      {
        auth: {
          persistSession: false,
          autoRefreshToken: false,
          detectSessionInUrl: false,
        },
      }
    );

    // Get authenticated user
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('Authorization header required');
    }

    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: userError } = await supabaseClient.auth.getUser(token);

    if (userError || !user) {
      console.error('❌ User auth error:', userError);
      throw new Error('User not authenticated');
    }

    console.log('✅ User authenticated:', user.id);

    // Parse request body
    const body: GenerateTopupLinkRequest = await req.json();
    console.log('📦 Request body:', body);

    // Validate required fields
    if (!body.cardId) {
      throw new Error('Missing required field: cardId');
    }

    // Fetch the card and verify ownership
    const { data: card, error: cardError } = await supabaseClient
      .from('issuing_cards')
      .select(`
        id,
        organization_id,
        group_id,
        cardholder_name,
        cardholder_email,
        card_status,
        card_last4,
        organizations (
          id,
          name,
          user_id
        )
      `)
      .eq('id', body.cardId)
      .single<IssuingCardRecord>();

    if (cardError || !card) {
      console.error('❌ Card lookup error:', cardError);
      throw new Error('Card not found');
    }

    // Verify user owns the organization
    const cardOrganization = Array.isArray(card.organizations)
      ? card.organizations[0]
      : card.organizations;

    if (!cardOrganization) {
      throw new Error('Card organization data is missing');
    }

    if (cardOrganization.user_id !== user.id) {
      throw new Error('Access denied: Card belongs to different organization');
    }

    // Check card is active
    if (card.card_status !== 'active') {
      throw new Error(`Cannot generate top-up link for ${card.card_status} card`);
    }

    console.log('✅ Card verified:', card.card_last4);

    // Generate secure token (32 bytes = 64 hex chars)
    const tokenBytes = new Uint8Array(32);
    crypto.getRandomValues(tokenBytes);
    const topupToken = Array.from(tokenBytes)
      .map(b => b.toString(16).padStart(2, '0'))
      .join('');

    // Calculate expiry (default 30 days)
    const expiryDays = body.expiryDays || 30;
    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + expiryDays);

    console.log('🔐 Generated token, expires:', expiresAt.toISOString());

    // Create pending load record with token
    const { data: loadRecord, error: loadError } = await supabaseClient
      .from('issuing_card_loads')
      .insert({
        card_id: card.id,
        organization_id: card.organization_id,
        group_id: card.group_id,
        amount: 0, // Will be set when parent actually loads funds
        source_type: 'parent_topup',
        payment_status: 'pending',
        topup_token: topupToken,
        topup_token_expires_at: expiresAt.toISOString(),
        parent_email: card.cardholder_email,
        notes: `Top-up link generated by ${user.email} for ${card.cardholder_name}`,
        metadata: {
          generated_by: user.id,
          generated_at: new Date().toISOString(),
          card_last4: card.card_last4,
        },
      })
      .select()
      .single();

    if (loadError) {
      console.error('❌ Error creating load record:', loadError);
      throw new Error(`Failed to create top-up link: ${loadError.message}`);
    }

    console.log('✅ Load record created:', loadRecord.id);

    // Log activity
    const { error: activityError } = await supabaseClient
      .from('issuing_activity_log')
      .insert({
        organization_id: card.organization_id,
        group_id: card.group_id,
        card_id: card.id,
        action: 'topup_link_generated',
        actor_type: 'admin',
        actor_user_id: user.id,
        actor_email: user.email,
        entity_type: 'card_load',
        entity_id: loadRecord.id,
        description: `Generated top-up link for ${card.cardholder_name} (•••• ${card.card_last4})`,
        metadata: {
          token_expires_at: expiresAt.toISOString(),
          parent_email: card.cardholder_email,
        },
      });

    if (activityError) {
      console.error('⚠️ Failed to log activity:', activityError);
      // Don't fail the whole operation
    }

    console.log('🎉 Top-up link generated successfully!');

    // Return success response with token
    return new Response(
      JSON.stringify({
        success: true,
        topupToken: topupToken,
        topupUrl: `/topup/${topupToken}`,
        expiresAt: expiresAt.toISOString(),
        cardholderName: card.cardholder_name,
        cardholderEmail: card.cardholder_email,
        cardLast4: card.card_last4,
        loadRecordId: loadRecord.id,
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );
  } catch (error: any) {
    console.error('❌ Error generating top-up link:', error);

    return new Response(
      JSON.stringify({
        error: error.message || 'Failed to generate top-up link',
        details: error.toString(),
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    );
  }
});
